#!/usr/bin/env python3
"""The constants table, generated from the RTL and the harness rather than typed.

WHY

Every number in this repository that describes the chip appears in at least
three places: the Verilog that makes it true, the Python that has to agree with
it, and the prose that explains it. Two of those three are checked against each
other by the tests. The third is checked by nobody, and a stale number in a
document is not a typo, it is an instruction to a future reader to build the
wrong host.

This repository has already shipped a document describing the wrong number of
sites after the design shrank, and a comment describing a chain length that no
longer exists. Neither broke anything and both would have been read as fact.

So the numbers are extracted from the source of truth and written out, and CI
fails if the generated table has drifted from the committed one. The generator
is the specification of where each number lives; if a number is not here, it is
because nothing yet reads it from the RTL, and that is worth knowing too.

USAGE

    tools/gen_constants.py              write docs/CONSTANTS.md
    tools/gen_constants.py --check      fail if the committed file has drifted
"""

import argparse
import os
import re
import subprocess
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
OUT = os.path.join(ROOT, "docs", "CONSTANTS.md")


def rtl(path, pattern, group=1):
    text = open(os.path.join(ROOT, path)).read()
    m = re.search(pattern, text, re.M)
    if not m:
        raise SystemExit(f"could not find {pattern!r} in {path}. The generator "
                         f"is the thing that has to be fixed, not the table.")
    return m.group(group)


def harness(name):
    sys.path.insert(0, os.path.join(ROOT, "harness"))
    from evofab import genome
    return getattr(genome, name)


def git(*args, default="unknown"):
    try:
        return subprocess.run(["git", "-C", ROOT, *args], capture_output=True,
                              text=True, check=True).stdout.strip()
    except Exception:
        return default


def collect():
    n_sites = int(rtl("src/project.v", r"^\s*`define N_SITES (\d+)"))
    site_w = int(rtl("src/project.v", r"localparam integer SITE_W\s*=\s*(\d+)"))
    global_w = int(rtl("src/project.v", r"localparam integer GLOBAL_W\s*=\s*(\d+)"))
    tdc_taps = int(rtl("src/project.v", r"localparam integer TDC_TAPS\s*=\s*(\d+)"))
    version = int(rtl("src/project.v", r"INSTR_VERSION = 8'd(\d+)"))
    coarse_w = int(rtl("src/tdc.v", r"reg \[(\d+):0\] wraps;")) + 1
    char_paths = int(rtl("src/project.v", r"5'd14: readout = 8'd(\d+);"))
    crc_w = harness("CRC_W")
    tiles = rtl("info.yaml", r"^\s*tiles:\s*\"?([0-9]+x[0-9]+)\"?")
    rows = [
        ("site count", n_sites, "src/project.v N_SITES"),
        ("site word, bits", site_w, "src/project.v SITE_W"),
        ("global word, bits", global_w, "src/project.v GLOBAL_W"),
        ("CRC, bits", crc_w, "harness/evofab/genome.py CRC_W"),
        ("scan payload, bits", global_w + site_w * n_sites, "derived"),
        ("scan frame, bits", global_w + site_w * n_sites + crc_w, "derived"),
        ("characterization paths", char_paths, "src/project.v readout slot 14"),
        ("TDC delay line, taps", tdc_taps, "src/project.v TDC_TAPS"),
        ("TDC coarse counter, bits", coarse_w, "src/tdc.v wraps"),
        ("TDC coarse range, taps", (2 ** coarse_w - 1) * 2 * tdc_taps,
         "derived: saturation is 2 traversals per count"),
        ("instrument version", version, "src/project.v INSTR_VERSION"),
        ("tiles", tiles, "info.yaml"),
    ]
    # Agreement with the harness, checked here rather than assumed. These are
    # the constants a host uses to address the chip; if they drift the host
    # addresses the wrong bits and nothing fails loudly.
    mismatches = []
    for name, got, want in [("GLOBAL_W", global_w, harness("GLOBAL_W")),
                            ("SITE_W", site_w, harness("SITE_W")),
                            ("TDC_TAPS", tdc_taps, harness("TDC_TAPS")),
                            ("INSTR_VERSION", version, harness("INSTR_VERSION"))]:
        if got != want:
            mismatches.append(f"{name}: RTL says {got}, "
                              f"harness/evofab/genome.py says {want}")
    return rows, mismatches


def render(rows):
    L = ["# Constants",
         "",
         "Generated by `tools/gen_constants.py`. Do not edit by hand; edit the",
         "RTL and regenerate. CI fails if this file and the source disagree.",
         "",
         "Every number here is read out of the thing that makes it true. The",
         "column on the right says which thing, so that a number that turns out",
         "to be wrong can be fixed where it is wrong rather than here.",
         "",
         "| constant | value | where it comes from |",
         "|---|---|---|"]
    for name, value, src in rows:
        L.append(f"| {name} | {value} | `{src}` |")
    L += ["",
          "## What the chip will tell you itself",
          "",
          "A host talking to an unfamiliar die does not have to trust this file.",
          "The readout selector reports the site count at slot 7, the global word",
          "width at slot 19, the instrument version at slot 20 and the site word",
          "width at slot 22, and `test/test.py` asserts each against the values",
          "above. A host that disagrees with the silicon finds out on the first",
          "frame instead of decoding twenty sites' worth of genome into the wrong",
          "fields.",
          ""]
    return "\n".join(L)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true")
    args = ap.parse_args()
    rows, mismatches = collect()
    if mismatches:
        for m in mismatches:
            print(f"FAIL: {m}", file=sys.stderr)
        return 1
    text = render(rows)
    if args.check:
        if not os.path.exists(OUT):
            print(f"FAIL: {OUT} does not exist. Run tools/gen_constants.py.",
                  file=sys.stderr)
            return 1
        have = open(OUT).read()
        if have != text:
            print("FAIL: docs/CONSTANTS.md has drifted from the source.\n"
                  "Run tools/gen_constants.py and commit the result.",
                  file=sys.stderr)
            import difflib
            sys.stderr.writelines(difflib.unified_diff(
                have.splitlines(True), text.splitlines(True),
                fromfile="committed", tofile="generated"))
            return 1
        print("docs/CONSTANTS.md agrees with the source")
        return 0
    with open(OUT, "w") as fh:
        fh.write(text)
    print(f"wrote {OUT}")
    print(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
