#!/usr/bin/env python3
"""The numeric half of the pre-registration, generated from the shipped build.

WHY GENERATED

predictions/RULES.md holds the judgements. This holds the numbers, and the
numbers should not be typed. Every one of them is a Liberty-plus-extraction
prediction that already exists inside the build's own SDF, and a value copied by
hand from a report into a document is a value that can be copied wrongly, copied
from a different corner, or quietly refreshed later from a better build.

So the prediction files are generated from one named artifact of one named
commit, they record which artifact and which commit, and regenerating them from
that commit reproduces them exactly. That is what makes the timestamp mean
something: not that a document existed on a date, but that the document is a
function of a build that existed on that date.

WHAT IT DOES NOT DO

It does not invent intervals. The interval on a Liberty-plus-extraction number
is a judgement about how far that model layer is from silicon, which is the very
thing the chip exists to measure, so it is stated once here as a rule with its
reasoning rather than tuned per row.

USAGE

    tools/prereg.py <sdf> [--spice spice_ladder.json] [--out predictions/generated]
"""

import argparse
import json
import os
import subprocess
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import tdc_range as tr  # noqa: E402

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# The interval on every Liberty-plus-extraction prediction below, as a fraction.
#
# Chosen once, with a reason, and applied to every row rather than tuned per row.
# Twenty percent is roughly what the open sky130 literature reports for
# Liberty-versus-silicon on delay, and it is deliberately WIDER than we expect to
# need for RATIOS and narrower than we expect to need for absolute delays. Both
# of those are predictions in themselves and both are falsifiable: if the ratios
# come back outside twenty percent this interval was too tight, and if every
# absolute delay lands inside it the open models are better than the literature
# says, which is a publishable finding either way.
INTERVAL = 0.20

# Ratios are a different quantity from delays. Most of what makes a Liberty
# delay wrong (a wire model, a corner, a temperature) moves both arms of a ratio
# the same way and cancels, so the interval on a ratio is tighter and is stated
# separately rather than inherited.
RATIO_INTERVAL = 0.10


def commit():
    try:
        return subprocess.run(["git", "-C", ROOT, "rev-parse", "HEAD"],
                              capture_output=True, text=True,
                              check=True).stdout.strip()
    except Exception:
        return "unknown"


def fit(xs, ys):
    n = len(xs)
    mx, my = sum(xs) / n, sum(ys) / n
    den = sum((x - mx) ** 2 for x in xs)
    m = sum((x - mx) * (y - my) for x, y in zip(xs, ys)) / den if den else 0.0
    b = my - m * mx
    resid = max(abs(y - (m * x + b)) for x, y in zip(xs, ys))
    return m, b, resid


HEAD = """# {title}

Generated by `tools/prereg.py` from `{sdf}`, corner `{corner}`, at commit
`{commit}`. Regenerating from that commit reproduces this file exactly.

**Model layer: the released sky130 Liberty view plus post place-and-route
extraction.** That is one of the three layers docs/MEASUREMENT_PROTOCOL.md names
and it is allowed to be wrong. Being wrong here does not indict SPICE and does
not indict Liberty alone; recording the layer is what keeps those separable.

Intervals are plus or minus {interval:.0%} on a delay and plus or minus
{ratio:.0%} on a ratio, for the reason given in `tools/prereg.py`. **No interval
is widened after a measurement.**

"""


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as fh:
        fh.write(text)
    print(f"wrote {path}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("sdf")
    ap.add_argument("--spice")
    ap.add_argument("--out", default=os.path.join(ROOT, "predictions", "generated"))
    ap.add_argument("--taps", type=int, default=32)
    args = ap.parse_args()

    if not os.path.exists(args.sdf):
        print(f"no SDF at {args.sdf}", file=sys.stderr)
        return 2
    by = tr.load_sdf(args.sdf)
    if not by:
        print("no cells parsed; that is not an SDF", file=sys.stderr)
        return 2

    corner = os.path.basename(os.path.dirname(args.sdf)) or "unknown"
    span = sum(v for k, v in by.items() if k.startswith("u_tdc.dl"))
    tap = span / args.taps
    period = 2 * span
    over = sum(by.get(k, 0.0) for k in (
        "u_char.lrt.g4.u", "u_char.lbuf[0].u.g2.u", "u_char.gate[0].u.u",
        "u_char.merge[0].u.g4.u", "u_char.merge_out.g2.u"))

    paths = {}
    for i, name in enumerate(tr.CHAR_PATHS):
        s = tr.series(by, f"u_char.p{i}.")
        if s:
            paths[name] = s + over
    if not paths:
        print("no characterization paths found in the SDF", file=sys.stderr)
        return 1

    rel = os.path.relpath(args.sdf, ROOT)
    head = dict(sdf=args.sdf if rel.startswith("..") else rel,
                corner=corner, commit=commit(),
                interval=INTERVAL, ratio=RATIO_INTERVAL)

    # ------------------------------------------------------------- the converter
    L = [HEAD.format(title="TDC, predicted", **head),
         "| quantity | predicted | interval | in taps |",
         "|---|---|---|---|",
         f"| mean tap delay | {tap*1000:.1f} ps | "
         f"{tap*1000*(1-INTERVAL):.1f} to {tap*1000*(1+INTERVAL):.1f} ps | 1 |",
         f"| one traversal, 32 taps | {span:.3f} ns | "
         f"{span*(1-INTERVAL):.3f} to {span*(1+INTERVAL):.3f} ns | 32 |",
         f"| ring period, 2 traversals | {period:.3f} ns | "
         f"{period*(1-INTERVAL):.3f} to {period*(1+INTERVAL):.3f} ns | 64 |",
         f"| fixed launch and merge overhead | {over:.3f} ns | "
         f"{over*(1-INTERVAL):.3f} to {over*(1+INTERVAL):.3f} ns | "
         f"{over/tap:.1f} |",
         "",
         "**Bin width spread across the 32 taps: predicted under 15 percent of a",
         "mean bin, one sigma.** This is the weakest prediction in the file and it",
         "is written down anyway. We have no basis for it beyond an order of",
         "magnitude, because it is a prediction about how badly this particular",
         "place and route distorts a hand built delay line, and nothing in the",
         "extraction reports that. It is measured by code density in study 2.",
         "",
         "**Falsified by:** a measured ring period outside the interval, which",
         "would invalidate every coarse counted reading at once; or a bin width",
         "spread so large that the mean tap is not a useful unit, which would mean",
         "every delay on this chip has to be quoted through the bin table and",
         "never as a tap count.",
         ""]
    write(os.path.join(args.out, "tdc.md"), "\n".join(L))

    # ------------------------------------------------------------- fixed paths
    L = [HEAD.format(title="Fixed characterization paths, predicted", **head),
         "Each number is the series chain plus the fixed launch and merge",
         f"overhead of {over:.3f} ns, which is charged to every reading and is",
         "not subtracted here because the host cannot subtract what it has not",
         "measured. The depth series fit below is how that overhead becomes",
         "separable.",
         "",
         "| path | predicted delay | interval | taps | ring periods |",
         "|---|---|---|---|---|"]
    for name in tr.CHAR_PATHS:
        if name not in paths:
            continue
        d = paths[name]
        L.append(f"| `{name}` | {d:.3f} ns | {d*(1-INTERVAL):.3f} to "
                 f"{d*(1+INTERVAL):.3f} ns | {d/tap:.1f} | {d/period:.2f} |")
    L += ["",
          "**Falsified by:** a measured delay outside its interval. That is the",
          "point of the file and it is expected to happen for some rows; which",
          "rows, and in which direction, is the result.",
          ""]
    write(os.path.join(args.out, "char_paths.md"), "\n".join(L))

    # ------------------------------------------------------------ depth series
    depths = [(2, "inv1_d2"), (4, "inv1_d4"), (8, "inv1_d8"), (16, "inv1_d16"),
              (24, "load_0"), (32, "inv1_d32")]
    pts = [(d, paths[n]) for d, n in depths if n in paths]
    L = [HEAD.format(title="Depth series, predicted", **head),
         "**This is the load bearing one.** Without a predicted slope the",
         "converter's calibration is unfalsifiable: any measured tap count can be",
         "turned into any delay by choosing a tap width afterwards. The slope",
         "predicts a delay per stage in TAPS, and the tap width predicted in",
         "`tdc.md` turns it into picoseconds. Both have to be right.",
         ""]
    if len(pts) >= 3:
        xs = [d for d, _ in pts]
        ys = [v for _, v in pts]
        m, b, resid = fit(xs, ys)
        L += ["| quantity | predicted | interval |",
              "|---|---|---|",
              f"| per stage delay, the slope | {m*1000:.1f} ps "
              f"({m/tap:.3f} taps) | {m*1000*(1-INTERVAL):.1f} to "
              f"{m*1000*(1+INTERVAL):.1f} ps |",
              f"| fixed offset, the intercept | {b:.3f} ns "
              f"({b/tap:.1f} taps) | {b*(1-INTERVAL):.3f} to "
              f"{b*(1+INTERVAL):.3f} ns |",
              f"| worst residual of the straight line fit | {resid*1000:.1f} ps "
              f"({resid/tap:.2f} taps) | under 1 tap |",
              "",
              "| depth | path | predicted |",
              "|---|---|---|"]
        for d, n in depths:
            if n in paths:
                L.append(f"| {d} | `{n}` | {paths[n]:.3f} ns |")
        L += ["",
              "**The linearity is a separate prediction from the slope.** If the",
              "series is not linear the intercept is not a constant and nothing",
              "else on this chip can be quoted against it, so the case that would",
              "invalidate the method is predicted rather than assumed away. The",
              "residual above is predicted to stay under one tap.",
              "",
              "**Depths 16 and 24 are reached by two structurally different paths**",
              "and are predicted to agree within one tap. That is a free",
              "repeatability check with no extra silicon, and a disagreement there",
              "is a disagreement about the instrument, not about depth.",
              "",
              "**Falsified by:** a measured slope outside its interval; a residual",
              "above one tap, which would retire the constant intercept and with",
              "it every number on this chip quoted against it; or the two depth",
              "16 paths disagreeing by more than a tap, which would say the",
              "instrument is not repeatable before any model is even consulted.",
              ""]
    else:
        L += ["The depth series could not be extracted from this SDF. That is a",
              "failure of the generator or of the build, not a prediction.", ""]
    write(os.path.join(args.out, "depth_series.md"), "\n".join(L))

    # -------------------------------------------------------- series and pairs
    L = [HEAD.format(title="Drive series, load series and the matched pairs",
                     **head),
         "Ratios first, because a ratio is the more defensible prediction: most",
         "of what makes a Liberty delay wrong moves both arms the same way and",
         "cancels. The absolute differences follow, with the repeat count each",
         "one needs.",
         ""]
    for label, group in [("Drive series, against x1",
                          ["drive_x1", "drive_x2", "drive_x4", "drive_x8"]),
                         ("Load series, against 0 sinks",
                          ["load_0", "load_1", "load_2", "load_4"])]:
        if group[0] not in paths:
            continue
        base = paths[group[0]]
        L += [f"### {label}", "",
              "| path | predicted | ratio to the first | interval on the ratio |",
              "|---|---|---|---|"]
        for n in group:
            if n not in paths:
                continue
            r = paths[n] / base
            L.append(f"| `{n}` | {paths[n]:.3f} ns | {r:.4f} | "
                     f"{r*(1-RATIO_INTERVAL):.4f} to "
                     f"{r*(1+RATIO_INTERVAL):.4f} |")
        L.append("")
    L += ["### The two matched pairs, and the differences that need repeats", "",
          "| comparison | predicted difference | taps | trials per arm |",
          "|---|---|---|---|"]
    for label, a, b in tr.COMPARISONS:
        if a not in paths or b not in paths:
            continue
        diff = abs(paths[a] - paths[b])
        nt = diff / tap
        need = max(1, int(18 * (1.0 / 12.0) / max(nt, 1e-9) ** 2 + 0.5))
        L.append(f"| {label} | {diff*1000:.0f} ps | {nt:.2f} | "
                 f"{1 if nt >= 3 else need} |")
    L += ["",
          "The trial counts assume the arrival DITHERS across bin boundaries.",
          "Whether it does is study 2 and it is measured before any of these is",
          "believed. See section 3 of predictions/RULES.md.",
          "",
          "**The load ladder pair is not predicted from this table.** Its number",
          "here is routing: the released Liberty view gives that pin one",
          "capacitance with no enable dependence, so the extraction has no",
          "mechanism to report and what varies between builds is wire. The same",
          "pair measured 7 ps on one build and 57 ps on the next with the circuit",
          "unchanged. Its prediction comes from SPICE and is below.",
          ""]

    if args.spice and os.path.exists(args.spice):
        d = json.load(open(args.spice))
        L += ["### The load ladder pair, from transistor level SPICE", "",
              "| corner | V | C | delta rise | delta fall |",
              "|---|---|---|---|---|"]
        for c in d["cases"]:
            L.append(f"| {c['corner']} | {c['vdd']:.2f} | {c['temp']:.0f} | "
                     f"{c['d_rise_ps']:+.1f} ps | {c['d_fall_ps']:+.1f} ps |")
        worst = max(max(abs(c["d_rise_ps"]), abs(c["d_fall_ps"]))
                    for c in d["cases"])
        best = min(min(abs(c["d_rise_ps"]), abs(c["d_fall_ps"]))
                   for c in d["cases"])
        tap_ps = tap * 1000
        L += ["",
              f"Worst case {worst:.1f} ps ({worst/tap_ps:.2f} taps), best case "
              f"{best:.1f} ps ({best/tap_ps:.2f} taps).", ""]
        if best / tap_ps >= 1:
            L.append("**Category: resolvable measurement.** One trial per "
                     "configuration reads it.")
        elif worst / tap_ps >= 1:
            L.append("**Category: repeated statistical measurement**, and only "
                     "if study 2 shows the arrival dithers. Otherwise it drops "
                     "to an upper bound.")
        else:
            L.append("**Category: upper bound.** The effect is below one tap "
                     "everywhere simulated. The row is reported as a bound at a "
                     "stated confidence level, not as a measurement that failed, "
                     "and the design is not changed to amplify it.")
        L.append("")
    else:
        L += ["### The load ladder pair, from SPICE", "",
              "**NOT YET RUN.** The `spice` workflow produces "
              "`spice_ladder.json`; pass it with `--spice`. Until then row 6 of "
              "docs/EXPERIMENT_MATRIX.md has no prediction and must not be given "
              "one from the table above.", ""]
    write(os.path.join(args.out, "series_and_pairs.md"), "\n".join(L))
    return 0


if __name__ == "__main__":
    sys.exit(main())
